### ISSUE TITLE
Repo setup todo

### ISSUE THREAD

**Issue by karlredman** [karlredman/karlredman.github.io#1]
* [x] Change menu Home button to point to github site
* [x] Change all references to site to github site
* [x] Change README.md file
    * Moving to new ticket
* [x] Remove site Resources from menu Temporary
* [x] archive old ghost blog posts from old site
* [x] ?? add email reference to opening statement
    * [x] Not gonna fix
